version: "3.3"
services:
        frontend:
                build: ./frontend
                ports:
                        - 1250:3499
        backend:
                build: ./api
                ports:
                        - 1290:80
        db:
                build: ./db
                ports:
                        - 1330:3306
                volumes:
                        - dbdata:/var/lib/mysql
volumes:
        dbdata: 
